######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 7 16:09:04 2012
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += testApp.h
SOURCES += main.cpp testApp.cpp
