# #####################################################################
# Automatically generated by qmake (1.07a) Mon Dec 10 14:59:21 2012
# #####################################################################
TEMPLATE = app
INCLUDEPATH += .
CONFIG += link_pkgconfig
PKGCONFIG += opencv

# Input
HEADERS += v4l2uvc.h \
    uvccapture.h \
    uvccapture.h
SOURCES += v4l2uvc.c \
    uvccapture.cpp \
    Video.cpp
LIBS += -ljpeg
