# #####################################################################
# Automatically generated by qmake (1.07a) Tue Jun 11 16:01:37 2013
# #####################################################################
TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .
CONFIG += link_pkgconfig
PKGCONFIG += opencv

# Input
SOURCES += main.cpp \
    capturethread.cpp
HEADERS += capturethread.h
