######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 7 16:54:31 2012
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += CaptureDevice.hpp MainWindow.hpp Prereqs.hpp
SOURCES += CaptureDevice.cpp main.cpp MainWindow.cpp
