######################################################################
# Automatically generated by qmake (1.07a) Fri Jun 14 11:55:08 2013
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .
CONFIG += link_pkgconfig
PKGCONFIG += opencv
# Input
SOURCES += camera_calibration.cpp
