######################################################################
# Automatically generated by qmake (1.07a) Fri May 24 05:34:29 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += FrameBuffer.h shader.h
SOURCES += Display.cpp FrameBuffer.cpp shader.cpp
