######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 7 14:22:02 2012
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += contrib_test_capture-example.c
