/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_capture (void)
{
  GtkWidget *capture;
  GtkWidget *vbox1;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport2;
  GtkWidget *picture;
  GtkWidget *table1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *brightness;
  GtkWidget *label6;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *contrast;
  GtkWidget *label7;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *gamma;
  GtkWidget *label8;
  GtkWidget *frame4;
  GtkWidget *alignment4;
  GtkWidget *saturation;
  GtkWidget *label9;
  GtkWidget *frame5;
  GtkWidget *alignment5;
  GtkWidget *xoff;
  GtkWidget *label10;
  GtkWidget *frame6;
  GtkWidget *alignment6;
  GtkWidget *yoff;
  GtkWidget *label11;

  capture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (capture, "capture");
  gtk_window_set_title (GTK_WINDOW (capture), _("capture"));
  gtk_window_set_destroy_with_parent (GTK_WINDOW (capture), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (capture), vbox1);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow3, 320, 240);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport2, "viewport2");
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport2);

  picture = gtk_drawing_area_new ();
  gtk_widget_set_name (picture, "picture");
  gtk_widget_show (picture);
  gtk_container_add (GTK_CONTAINER (viewport2), picture);
  gtk_widget_set_size_request (picture, 640, 480);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 1);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 1);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_table_attach (GTK_TABLE (table1), frame1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame1), 0.04, 0.5);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  brightness = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (100, 0, 255, 0, 0, 0)));
  gtk_widget_set_name (brightness, "brightness");
  gtk_widget_show (brightness);
  gtk_container_add (GTK_CONTAINER (alignment1), brightness);
  gtk_scale_set_digits (GTK_SCALE (brightness), 0);

  label6 = gtk_label_new (_("<b>bright</b>"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label6);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_show (frame2);
  gtk_table_attach (GTK_TABLE (table1), frame2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame2), 0.04, 0.5);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  contrast = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (40, 0, 255, 0, 0, 0)));
  gtk_widget_set_name (contrast, "contrast");
  gtk_widget_show (contrast);
  gtk_container_add (GTK_CONTAINER (alignment2), contrast);
  gtk_scale_set_digits (GTK_SCALE (contrast), 0);

  label7 = gtk_label_new (_("<b>contrast</b>"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label7);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_show (frame3);
  gtk_table_attach (GTK_TABLE (table1), frame3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame3), 0.04, 0.5);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 0, 12, 0);

  gamma = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (30, 0, 255, 0, 0, 0)));
  gtk_widget_set_name (gamma, "gamma");
  gtk_widget_show (gamma);
  gtk_container_add (GTK_CONTAINER (alignment3), gamma);
  gtk_scale_set_digits (GTK_SCALE (gamma), 0);

  label8 = gtk_label_new (_("<b>gamma</b>"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label8);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_show (frame4);
  gtk_table_attach (GTK_TABLE (table1), frame4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame4), 0.04, 0.5);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (frame4), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 12, 0);

  saturation = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (20, 0, 255, 0, 0, 0)));
  gtk_widget_set_name (saturation, "saturation");
  gtk_widget_show (saturation);
  gtk_container_add (GTK_CONTAINER (alignment4), saturation);
  gtk_scale_set_digits (GTK_SCALE (saturation), 0);

  label9 = gtk_label_new (_("<b>saturation</b>"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label9);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame5, "frame5");
  gtk_widget_show (frame5);
  gtk_table_attach (GTK_TABLE (table1), frame5, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame5), 0.04, 0.5);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame5), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  xoff = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_set_name (xoff, "xoff");
  gtk_widget_show (xoff);
  gtk_container_add (GTK_CONTAINER (alignment5), xoff);
  gtk_scale_set_digits (GTK_SCALE (xoff), 0);

  label10 = gtk_label_new (_("<b>x off</b>"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label10);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame6, "frame6");
  gtk_widget_show (frame6);
  gtk_table_attach (GTK_TABLE (table1), frame6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame6), 0.04, 0.5);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment6, "alignment6");
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (frame6), alignment6);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment6), 0, 0, 12, 0);

  yoff = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_set_name (yoff, "yoff");
  gtk_widget_show (yoff);
  gtk_container_add (GTK_CONTAINER (alignment6), yoff);
  gtk_scale_set_digits (GTK_SCALE (yoff), 0);

  label11 = gtk_label_new (_("<b>y off</b>"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label11);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  g_signal_connect ((gpointer) capture, "delete_event",
                    G_CALLBACK (on_capture_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) brightness, "value_changed",
                    G_CALLBACK (on_brightness_value_changed),
                    NULL);
  g_signal_connect ((gpointer) contrast, "value_changed",
                    G_CALLBACK (on_contrast_value_changed),
                    NULL);
  g_signal_connect ((gpointer) gamma, "value_changed",
                    G_CALLBACK (on_gamma_value_changed),
                    NULL);
  g_signal_connect ((gpointer) saturation, "value_changed",
                    G_CALLBACK (on_saturation_value_changed),
                    NULL);
  g_signal_connect ((gpointer) xoff, "value_changed",
                    G_CALLBACK (on_xoff_value_changed),
                    NULL);
  g_signal_connect ((gpointer) yoff, "value_changed",
                    G_CALLBACK (on_yoff_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (capture, capture, "capture");
  GLADE_HOOKUP_OBJECT (capture, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (capture, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (capture, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (capture, picture, "picture");
  GLADE_HOOKUP_OBJECT (capture, table1, "table1");
  GLADE_HOOKUP_OBJECT (capture, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (capture, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (capture, brightness, "brightness");
  GLADE_HOOKUP_OBJECT (capture, label6, "label6");
  GLADE_HOOKUP_OBJECT (capture, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (capture, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (capture, contrast, "contrast");
  GLADE_HOOKUP_OBJECT (capture, label7, "label7");
  GLADE_HOOKUP_OBJECT (capture, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (capture, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (capture, gamma, "gamma");
  GLADE_HOOKUP_OBJECT (capture, label8, "label8");
  GLADE_HOOKUP_OBJECT (capture, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (capture, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (capture, saturation, "saturation");
  GLADE_HOOKUP_OBJECT (capture, label9, "label9");
  GLADE_HOOKUP_OBJECT (capture, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (capture, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (capture, xoff, "xoff");
  GLADE_HOOKUP_OBJECT (capture, label10, "label10");
  GLADE_HOOKUP_OBJECT (capture, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (capture, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (capture, yoff, "yoff");
  GLADE_HOOKUP_OBJECT (capture, label11, "label11");

  return capture;
}

