# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtCamera
DESTDIR = ./
QT += core gui
CONFIG += release
DEFINES +=
CONFIG += link_pkgconfig
PKGCONFIG += opencv

DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(QtCamera.pri)
